export const ACCESS_TOKEN_INJECTION_TOKENS = {
  REPOSITORY: {
    ACCESS_TOKEN: 'ACCESS_TOKEN_REPOSITORY',
  },
  SERVICE: {
    ACCESS_TOKEN: 'ACCESS_TOKEN_SERVICE',
  },
  GUARD: {
    ACCESS_TOKEN: 'ACCESS_TOKEN_GUARD',
  },
} as const;
