name: nanoe-api
services:
  - name: api
    github:
      repo: your-username/nanoe-be
      branch: main
    dockerfile_path: Dockerfile
    dockerfile_target: production
    http_port: 3000
    instance_size_slug: basic-xxs
    instance_count: 1
    envs:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: ${db.DATABASE_URL}
      - key: JWT_SECRET
        value: your-secret
        type: SECRET
      - key: PORT
        value: '3000'
      - key: API_VERSION
        value: '1'
      - key: API_PREFIX
        value: 'api/v'
      - key: API_SUPPORTED_VERSIONS
        value: '1,2'
    routes:
      - path: /api
databases:
  - name: db
    engine: PG
    version: '16'
    production: true
