/**
 * Constants for member activity actions
 */
export const ACTIVITY_ACTIONS = {
  INVITATION_SENT: 'INVITATION_SENT',
  REGISTRATION_INVITATION_SENT: 'REGISTRATION_INVITATION_SENT',
  MEMBER_INVITED: 'MEMBER_INVITED',
  UPDATE: 'UPDATE',
  REMOVE: 'REMOVE',
  INVITATION_ACCEPTED: 'INVITATION_ACCEPTED',
  INVITATION_DECLINED: 'INVITATION_DECLINED',
  REGISTRATION_COMPLETED: 'REGISTRATION_COMPLETED',
} as const;

export type ActivityAction =
  (typeof ACTIVITY_ACTIONS)[keyof typeof ACTIVITY_ACTIONS];
