name: CI Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:latest
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      postgres:
        image: postgres:16
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      NODE_ENV: test
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/test_db
      REDIS_HOST: localhost
      REDIS_PORT: 6379
      JWT_SECRET: test-jwt-secret-for-ci
      COOKIE_SECRET: test-cookie-secret-for-ci
      ENCRYPTION_KEY: test-encryption-key
      APP_URL: http://localhost:3000
      FRONTEND_URL: http://localhost:8080
      API_PREFIX: api/v
      API_VERSION: 1
      LOG_LEVEL: info
      FEATURE_EMAIL_ENABLED: false
      DEPLOYMENT_TYPE: cloud
      SETUP_TOKEN: ${{ secrets.SETUP_TOKEN }}

    steps:
      - name: ':inbox_tray: Checkout Repository'
        uses: actions/checkout@v4

      - name: ':green_circle: Setup Node.js'
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: ':package: Install Dependencies'
        run: |
          npm install
          npm install @nestjs-modules/mailer@2.0.0
          npm prune

      - name: ':wrench: Initialize Database'
        run: npx prisma migrate deploy

      - name: ':art: Run Lint Checks'
        run: npm run lint

      - name: ':test_tube: Run Unit Tests'
        run: npm run test -- --coverage

      - name: ':rocket: Run E2E Tests'
        run: |
          # Set a timeout for the E2E tests
          timeout 60s npm run test:e2e || (echo "E2E tests timed out after 60 seconds" && exit 1)

      - name: ':package: Build Application'
        run: npm run build

      - name: ':white_check_mark: Complete'
        run: echo "CI pipeline finished successfully!"
